### PR TITLE
Correct Facebook API (v.8.0, current API)

### PR DESCRIPTION
**Pull request by sviluppomania**
Correct Facebook API (v.8.0, current API)

### CODE REVIEW

**Comment by miled** [comment]
It might be better to submit a PR to [hybridauth](https://github.com/hybridauth/hybridauth). We're using that library as it is, and I don't want to maintain a patched version of it.

**Comment by sviluppomania** [comment]
@miled  https://github.com/hybridauth/hybridauth/pull/1248

**Comment by miled** [comment]
Sure. I'll update it when they release hybridauth 3.6.

**Comment by jimi008** [comment]
@sviluppomania  @miled  Before merging this into the master, there is a recent change in API 8.0 that needs to be addressed. Please see below. 

>

**Pull request closed without merging**
